### ISSUE TITLE
Questions about another project：kdl_rmpflow

### ISSUE THREAD

**Issue by Shihao-Liang** [sageshoyu/QuatDMP#1]
I am very sorry to contact you in this way due to your another project kdl_ rmpflow does not have the issues function. I can only ask questions here.

when I run rmp_example_sparse.py,  I found it import "rmp_from_urdf" "RotZProjection"  "RotYProjection""RotXProjection" from kdl_rmpflow/rmp/kdl_rmp.py.
But in kdl_rmpflow/rmp/kdl_rmp.py ,it dosen't have such function.   So the program can't run .

Whether your kdl_rmp.py uploaded the wrong version？ sincerely await your reply.

Thanks very much!

**Comment by sageshoyu** [comment]
Hello,

Yes, you're right - this problem has come up because there are different versions of the project and I mixed up exactly which commits to push towars the end. However, at a high level, this was a project that was started a year and a half ago and not under active development at the moment. A warning if you intend to use this project - most of this code was developed the summer when Python 2  was dropped and before ROS/ROS-associated libraries switched Python versions, so codebase itself relies on a hand-hacked version of  KDL to do all the arm-kinematics math.

If you're interested in getting RMPs to work for robot arms, there are MUCH cleaner implementations out there. You can either use the repository this project was based on (though you'll have to reimplement the linkage kinematics math): [multi-robot-rmpflow](https://github.com/gtrll/multi-robot-rmpflow) or more recently [RMP2](https://github.com/UWRobotLearning/rmp2). 

Hope this helps!
